### PR TITLE
allow flask 2.0, bump to version 2.0.1

### PR DESCRIPTION
**Pull request by jvllmr**
pytest went smoothly and flask-buzz didn't cause any problems when using it in my current project

### CODE REVIEW

**Comment by jvllmr** [comment]
Any thoughts to this?

**Comment by jvllmr** [comment]
The PR [#259](https://github.com/dusktreader/flask-praetorian/pull/259) in flask-praetorian got merged already, but it doesn't take effect when flask-buzz won't allow usage of flask 2.0.

**Review by dsposito-ubtech — APPROVED** [review]

**Review by dsposito-ubtech — APPROVED** [review]

**Comment by jvllmr** [comment]
@dusktreader

**Comment by dusktreader** [comment]
Merged and published to pypi

**Pull request merged**
